### ISSUE TITLE
APK/F-Droid

### ISSUE THREAD

**Issue by RobinSchapendonk** [Netlob/magiscore#25]
Is er een manier om een apk te maken/downloaden, of beschikbaar te maken op F-Droid?

BTW, thx namens zo ongeveer de hele school 🤣

**Comment by Netlob** [comment]
ik kan je de apk sturen

**Comment by RobinSchapendonk** [comment]
k thx, vreemd dat aurora (gemairo en magiscore beide geen result) hem niet heeft tho, maar die apk werkt!
