### ISSUE TITLE
Bug: Cijfers die geen heel getal meetellen gaan naar 0 meetellen.

### ISSUE THREAD

**Issue by laurens-vrh** [netlob/magiscore#26]
Ik wist ni hoe ik dit moest schrijven maar ja.
Als een cijfers bevoorbeeld 0,5 meetelt (minder dan 1) dan staat er geen 0,5 maar gewoon 0 en wordt het cijfer ook niet meegeteld in je gemiddeldes.

**Comment by Netlob** [comment]
ja sorry maar heb atm geen tijd meer om gemairo te werken. je kan een PR maken en dan ga ik proberen die te uploaden, maar heb laatst per ongeluk m'n laptop gewiped dus weet niet of ik überhaupt nog kan builden lol

**Comment by MrWouterNL** [comment]
shi laptop gewiped

**Comment by stingalleman** [comment]
laptop weg gone loes
