### ISSUE TITLE
Moet betalen voor Gemairo (Aurora Store)

### ISSUE THREAD

**Issue by MarcOsiris** [netlob/magiscore#67]
Ik kan de app niet downloaden op mijn telefoon (een Google Pixel 7a met [CalyxOS](https://calyxos.org/)) omdat ik ervoor moet betalen. Er staat: Download Failed, app not purchased. Dit zou ook door Aurora Store of Calyx kunnen liggen, maar het leek me toch verstandig om het even te laten weten.

**Comment by netlob** [comment]
Je kan de app alleen via Google Play downloaden

**Comment by MarcOsiris** [comment]
Gaat hier in de toekomst nog verandering in komen?

**Comment by OpenSourceSimon** [comment]
Kan je niet gewoon via een website de APK van de google play downloaden en die installeren?

**Comment by MarcOsiris** [comment]
Helaas is dit niet mogelijk op Calyx. Ik ga waarschijnlijk Graphene installeren, waardoor ik ook toegang heb tot de Playstore. Maar terugkomend op mijn vraag: gaat er ooit support komen buiten de Playstore (APK, F-Droid, Aurora Store etc.)?

**Comment by dukesteen** [comment]
Waarschijnlijk niet
